#!/usr/bin/perl

# Copyright (c) 2010, David Davis - http://xant.us/

# WebSocket Example 1
# Powered by Mojo - http://mojolicious.org/ - http://github.com/kraih/mojo
# and web-socket-js - http://github.com/gimite/web-socket-js

use FindBin;
die "You need to run 'git submodule update --init' to fetch the example requirements\n"
    unless -d "$FindBin::Bin/../mojo/lib";

use lib "$FindBin::Bin/../mojo/lib";
use strict;
use warnings;

use Mojolicious::Lite;

@ARGV = qw( daemon ) unless @ARGV;

websocket '/' => sub {
    my $self = shift;
    $self->send_message( 'Congratulations, your Mojo is working!' );
    $self->finished( sub {
        # put your disconnected client handling here
    } );
    $self->receive_message(sub {
        my ( $self, $message ) = @_;
        $self->send_message( 'echo:'.$message );
    });
};

get '/' => 'index';

# see script/flash-policy-server
print "Remember, you need to also run script/flash-policy-server as root for this to work...\n";

app->start;

1;

__DATA__

@@ index.html.ep
% my $url = $self->req->url->to_abs->scheme( 'ws' )->path( '/' );
<!doctype html>
<html>
<head>
    <title>Mojo Websocket Demo</title>
    <script type="text/javascript" src="swfobject.js"></script>
    <script type="text/javascript" src="FABridge.js"></script>
    <script type="text/javascript" src="web_socket.js"></script>
    <script type="text/javascript">

        // Set URL of your WebSocketMain.swf here:
        WebSocket.__swfLocation = 'WebSocketMain.swf';

        var ws, input, log;

        function init() {
            input = document.getElementById( 'input' );
            log = document.getElementById( 'log' );

            // Connect to Web Socket.
            ws = new WebSocket( '<%= $url %>' );

            // Set event handlers.
            ws.onopen = function() {
                output( 'onopen' );
                ws.send( 'test' );
            };
            ws.onmessage = function(e) {
                // e.data contains received string.
                output( 'onmessage: ' + e.data );
            };
            ws.onclose = function() {
                output( 'onclose' );
            };
        }

        function onSubmit() {
            ws.send( input.value );
            output( 'send: ' + input.value );
            input.value = '';
            try{ input.focus(); } catch(e) { };
        }

        function onCloseClick() {
            ws.close();
        }

        function output(str) {
            var escaped = str.replace( /&/, '&amp;' ).replace( /</, '&lt;' ).
                replace( />/, '&gt;' ).replace( /"/, '&quot;' );
            log.innerHTML = escaped + '<br>' + log.innerHTML;
        }

        window.onload = init;
    </script>
</head>
<body>
  <form onsubmit="onSubmit(); return false;">
    <input type="text" id="input">
    <input type="submit" value="Send">
    <button onclick="onCloseClick(); return false;">disconnect</button>
  </form>
  <div id="log"></div>
</body>
</html>

